[package]
name = "sol_ji_service"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
anyhow = "1"
base64 = "0.22"
borsh = "1"
sha2 = "0.10"
solana-sdk = "2.1"
solana-client = "2.1"
solana-transaction-status = "2.1"
solana-account-decoder = "2.1"
tokio-stream = "0.1"
dotenvy = "0.15"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sqlx = { version = "0.7", features = [
    "mysql",
    "runtime-tokio-rustls",
    "macros",
    "chrono",
    "json",
] }
chrono = { version = "0.4", features = ["serde"] }

# SQLx（MySQL 驱动 + Tokio 运行时 + rustls TLS）
# Actix Web
actix-web = "4"
# CORS
actix-cors = "0.7"
