# docker-compose.yml
version: '3.8'

services:
  # Nginx reverse proxy service
  nginx:
    image: nginx:alpine
    container_name: solji_nginx
    restart: always
    ports:
      - "8091:80"
    # network_mode: "host"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - sonia-indexer


  # indexer services
  sonia-indexer:
      image: sonia831/solji-indexer:v4.4.5
      container_name: solji_indexer_sonia
      restart: always
      # network_mode: "host"
      environment:
        - RUST_LOG=trace
        - API_PORT=8080
        - DATABASE_URL=mysql://root:Solji123@185.234.74.185:33306/solji_db
        - RPC_URL=https://api.devnet.solana.com
        - PROGRAM_ID=D9immZaczS2ASFqqSux2iCCAaFat7vcusB1PQ2SW6d95
        - PINATA_JWT=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySW5mb3JtYXRpb24iOnsiaWQiOiI0NjdlZmM3My1lZDkwLTRhYmMtYTczNy1jMDNhMjY5MTBmMDciLCJlbWFpbCI6ImNodWhlbWlhb0BnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwicGluX3BvbGljeSI6eyJyZWdpb25zIjpbeyJkZXNpcmVkUmVwbGljYXRpb25Db3VudCI6MSwiaWQiOiJOWUMxIn1dLCJ2ZXJzaW9uIjoxfSwibWZhX2VuYWJsZWQiOmZhbHNlLCJzdGF0dXMiOiJBQ1RJVkUifSwiYXV0aGVudGljYXRpb25UeXBlIjoic2NvcGVkS2V5Iiwic2NvcGVkS2V5S2V5IjoiNTg4NGUxNDY4NGFlZGY2NWUyNTYiLCJzY29wZWRLZXlTZWNyZXQiOiI2ZjkzOTJjNTVkZGM0Yzg4N2E1MWVhN2FlMWY2ODM2MThmNzNiNjJmMzE4NDM2MDQxNWRiMzEyNThhZWY3ZTk1IiwiZXhwIjoxNzc1NTQyOTc5fQ.6p7STAl83z6gDit--fLbW6k1EvEfVJgNKEOcblvS1SQ
        - PINATA_API_URL=https://api.pinata.cloud/pinning/pinFileToIPFS
        - PINATA_GATEWAY=https://solji.mypinata.cloud/ipfs
