# nginx.conf
events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    resolver 127.0.0.11 valid=5s;

    upstream solji_backend {
       server sonia-indexer:8080;
    }

    server {
        listen 80;
        server_name _;
        # ...
        location /api/ {
            proxy_pass http://solji_backend;
            # ...
        }
        location /health {
            proxy_pass http://solji_backend/health;
        }
        location / {
            proxy_pass http://solji_backend;
        }
    }
}
